### ISSUE TITLE
Add GitHub repository description

### ISSUE THREAD

**Issue by zenorocha** [JaySunSyn/jay-icons#1]
By doing that you'll make it easier for people to find your project on customelements.io.

https://customelements.io/JaySunSyn/jay-icons/

**Comment by JaySunSyn** [comment]
Thanks!

Do you know why https://github.com/JaySunSyn/jay-icons is not listed on
customelements.io?



On 28 January 2016 at 17:02, Zeno Rocha <notifications@github.com> wrote:

> By doing that you'll make it easier for people to find your project on
> customelements.io.
>
> https://customelements.io/JaySunSyn/jay-icons/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JaySunSyn/jay-icons/issues/1>.
>



-- 


Jalal Fathi
i make ideas real

w: www.jalal.io
m: j@jalal.io
p: +43 660 21 46 241 <%2B436602146241>
s: jalalfathi
h: call.jalal.io


k: w = website, m = mail, p = phone, s = skype, h = hangouts, k = key

--
Sign up for Capacitor <http://teams.jalal.io> and get started with a
startup development team this week!
